version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    volumes:
      - ./nginx/nginx-setup.conf:/etc/nginx/conf.d/default.conf:ro
      - media_volume:/app/media
      - static_volume:/app/static
    depends_on:
      - django
    networks:
      - app_network

  postgres:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./logs:/var/log/postgresql
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
      - ./pg_hba.conf:/etc/postgresql/pg_hba.conf
    env_file:
      - ./.env
    command: ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]
    networks:
      - app_network

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - ./.env
    networks:
      - app_network

  celery-worker:
    build: .
    command: celery -A config worker --loglevel=info
    environment:
      - ./.env
    depends_on:
      - rabbitmq
    networks:
      - app_network

  django:
    build:
      context: .
    depends_on:
      - postgres
      - rabbitmq
      - celery-worker
    env_file:
      - ./.env
    volumes:
      - .:/app
      - media_volume:/app/media
      - static_volume:/app/static
    ports:
      - "8000:8000"
    command: ["gunicorn", "--bind", "0.0.0.0:8000", "config.wsgi:application"]
    networks:
      - app_network

  redis:
    restart: unless-stopped
    image: redis:7.2.4-alpine
    expose:
      - 6379
    networks:
      - app_network


volumes:
  postgres_data:
  media_volume:
  static_volume:
  logs:
    driver: local

networks:
  app_network:
    driver: bridge