version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    volumes:
      - ./nginx/nginx-setup.conf:/etc/nginx/conf.d/default.conf:ro
      - media_volume:/app/media
      - static_volume:/app/static
    depends_on:
      - django

  postgres:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - ./.env

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: test
      RABBITMQ_DEFAULT_PASS: qwerty

  celery-worker:
    build: .
    command: celery -A config worker --loglevel=info
    environment:
      - CELERY_BROKER_TRANSPORT_URL=amqp://test:qwerty@rabbitmq:5672//
      - DATABASE_NAME=financial
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_HOST=postgres
    depends_on:
      - rabbitmq

  django:
    build:
      context: .
    depends_on:
      - postgres
      - rabbitmq
      - celery-worker
    env_file:
      - ./.env
    volumes:
      - .:/app
      - media_volume:/app/media
      - static_volume:/app/static
    ports:
      - "8001:8001"
    command: ["gunicorn", "--bind", "0.0.0.0:8001", "config.wsgi:application"]

  redis:
    restart: unless-stopped
    image: redis:7.2.4-alpine
    expose:
      - 6379


volumes:
  postgres_data:
  media_volume:
  static_volume:
