version: '3.8'

services:

  postgres:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=financial

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  celery-worker:
    build: .
    command: celery -A config worker --loglevel=info
    networks:
      - mainapp
    environment:
      - CELERY_BROKER_TRANSPORT_URL=amqp://guest:guest@rabbitmq:5672//
      - DATABASE_NAME=financial
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_HOST=postgres
    depends_on:
      - rabbitmq

  django:
    build:
      context: .
    depends_on:
      - postgres
      - rabbitmq
      - celery-worker
    env_file:
      - ./.env
    volumes:
      - .:/app
    networks:
      - mainapp
    ports:
      - "8000:8000"
    command: ["gunicorn", "--bind", "0.0.0.0:8000", "config.wsgi:application"]


volumes:
  postgres_data:

networks:
  mainapp: