# Generated by Django 5.0 on 2023-12-16 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Financial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predsedatelSovetaDirektorov', models.CharField(blank=True, max_length=255, null=True)),
                ('predsedatel_pravleniya', models.CharField(blank=True, max_length=100, null=True)),
                ('sovet_direktorov', models.CharField(blank=True, max_length=100, null=True)),
                ('chleny_pravleniya', models.CharField(blank=True, max_length=100, null=True)),
                ('glavnyy_buhgalter', models.CharField(blank=True, max_length=100, null=True)),
                ('bin', models.CharField(max_length=20, null=True)),
                ('address', models.TextField(null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('fax', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('bank_vtorogo_urovnya', models.JSONField(blank=True, default=list, null=True)),
                ('kastodian', models.JSONField(blank=True, default=list, null=True)),
                ('bankovskie_holdingi', models.JSONField(blank=True, default=list, null=True)),
            ],
        ),
    ]
