# Generated by Django 5.0 on 2023-12-07 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Financial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predsedatelSovetaDirektorov', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
