# Generated by Django 5.0 on 2023-12-16 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualmodel',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
    ]
