# Generated by Django 5.0 on 2023-12-16 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_individualmodel_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualmodel',
            name='is_superuser',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='individualmodel',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Admin'), (2, 'Manager'), (3, 'Client')], default=3, null=True),
        ),
    ]
