# Generated by Django 5.0 on 2023-12-17 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_individualmodel_is_superuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualmodel',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
