# Generated by Django 5.0 on 2024-01-04 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_appointmentmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointmentmodel',
            old_name='notes',
            new_name='summary',
        ),
        migrations.RemoveField(
            model_name='appointmentmodel',
            name='treat_type',
        ),
        migrations.AddField(
            model_name='appointmentmodel',
            name='title',
            field=models.CharField(default='new event', max_length=255),
        ),
    ]
