# Generated by Django 5.0 on 2024-01-08 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_appointmentmodel_appointment_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentmodel',
            name='appointment_time',
        ),
    ]
