# Generated by Django 5.0 on 2024-12-26 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_errorfeedback'),
        ('users', '0012_alter_book_author_alter_book_description_and_more'),
    ]

    operations = [
    ]
