# Generated by Django 5.0 on 2024-12-30 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_individualmodel_is_phone_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualmodel',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
