# Generated by Django 5.0 on 2024-03-05 07:08

from django.db import migrations


def populate_title_en(apps, schema_editor):
    Article = apps.get_model('articles', 'Article')
    for article in Article.objects.all():
        # Copying the value of 'title' to 'title_en'
        article.title_en = article.title
        article.save()


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_article_content_en_article_content_kk_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_title_en),
    ]
