# Generated by Django 5.0 on 2024-03-05 07:13

from django.db import migrations

def populate_content_en(apps, schema_editor):
    Article = apps.get_model('articles', 'Article')
    for article in Article.objects.all():
        # Copying the value of 'content' to 'content_en'
        article.content_en = article.content
        article.save(update_fields=['content_en'])

class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_populate_title_en'),
    ]

    operations = [
        migrations.RunPython(populate_content_en),
    ]
